// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package msgexamplepb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MSG struct {
	MsgId                int32    `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgText              string   `protobuf:"bytes,2,opt,name=msg_text,json=msgText,proto3" json:"msg_text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MSG) Reset()         { *m = MSG{} }
func (m *MSG) String() string { return proto.CompactTextString(m) }
func (*MSG) ProtoMessage()    {}
func (*MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MSG.Unmarshal(m, b)
}
func (m *MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MSG.Marshal(b, m, deterministic)
}
func (m *MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MSG.Merge(m, src)
}
func (m *MSG) XXX_Size() int {
	return xxx_messageInfo_MSG.Size(m)
}
func (m *MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_MSG proto.InternalMessageInfo

func (m *MSG) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *MSG) GetMsgText() string {
	if m != nil {
		return m.MsgText
	}
	return ""
}

type MsgRequest struct {
	Msg                  *MSG     `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRequest) Reset()         { *m = MsgRequest{} }
func (m *MsgRequest) String() string { return proto.CompactTextString(m) }
func (*MsgRequest) ProtoMessage()    {}
func (*MsgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *MsgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRequest.Unmarshal(m, b)
}
func (m *MsgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRequest.Marshal(b, m, deterministic)
}
func (m *MsgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequest.Merge(m, src)
}
func (m *MsgRequest) XXX_Size() int {
	return xxx_messageInfo_MsgRequest.Size(m)
}
func (m *MsgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequest proto.InternalMessageInfo

func (m *MsgRequest) GetMsg() *MSG {
	if m != nil {
		return m.Msg
	}
	return nil
}

type MsgResp struct {
	Recvmsg              string   `protobuf:"bytes,1,opt,name=recvmsg,proto3" json:"recvmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgResp) Reset()         { *m = MsgResp{} }
func (m *MsgResp) String() string { return proto.CompactTextString(m) }
func (*MsgResp) ProtoMessage()    {}
func (*MsgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *MsgResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgResp.Unmarshal(m, b)
}
func (m *MsgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgResp.Marshal(b, m, deterministic)
}
func (m *MsgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResp.Merge(m, src)
}
func (m *MsgResp) XXX_Size() int {
	return xxx_messageInfo_MsgResp.Size(m)
}
func (m *MsgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResp.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResp proto.InternalMessageInfo

func (m *MsgResp) GetRecvmsg() string {
	if m != nil {
		return m.Recvmsg
	}
	return ""
}

func init() {
	proto.RegisterType((*MSG)(nil), "msgexample.MSG")
	proto.RegisterType((*MsgRequest)(nil), "msgexample.MsgRequest")
	proto.RegisterType((*MsgResp)(nil), "msgexample.MsgResp")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xca, 0x2d, 0x4e, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8,
	0x49, 0x55, 0x32, 0xe7, 0x62, 0xf6, 0x0d, 0x76, 0x17, 0x12, 0xe5, 0x62, 0xcb, 0x2d, 0x4e, 0x8f,
	0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0xcd, 0x2d, 0x4e, 0xf7, 0x4c, 0x11,
	0x92, 0xe4, 0xe2, 0x00, 0x09, 0x97, 0xa4, 0x56, 0x94, 0x48, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06,
	0xb1, 0xe7, 0x16, 0xa7, 0x87, 0xa4, 0x56, 0x94, 0x28, 0xe9, 0x73, 0x71, 0xf9, 0x16, 0xa7, 0x07,
	0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x29, 0x72, 0x31, 0xe7, 0x16, 0xa7, 0x83, 0x35, 0x73,
	0x1b, 0xf1, 0xeb, 0x21, 0x2c, 0xd0, 0xf3, 0x0d, 0x76, 0x0f, 0x02, 0xc9, 0x29, 0x29, 0x73, 0xb1,
	0x83, 0x35, 0x14, 0x17, 0x08, 0x49, 0x70, 0xb1, 0x17, 0xa5, 0x26, 0x97, 0xc1, 0x74, 0x70, 0x06,
	0xc1, 0xb8, 0x46, 0xce, 0x60, 0x53, 0x83, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x4c, 0xb9,
	0x58, 0x82, 0x53, 0xf3, 0x52, 0x84, 0xc4, 0x50, 0x0c, 0x84, 0xdb, 0x2a, 0x25, 0x8c, 0x21, 0x5e,
	0x5c, 0xa0, 0xc4, 0xe0, 0xc4, 0x17, 0xc5, 0x83, 0x10, 0x2f, 0x48, 0x4a, 0x62, 0x03, 0x7b, 0xdb,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x20, 0x3f, 0x50, 0x03, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgServiceClient is the client API for MsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgServiceClient interface {
	Send(ctx context.Context, in *MsgRequest, opts ...grpc.CallOption) (*MsgResp, error)
}

type msgServiceClient struct {
	cc *grpc.ClientConn
}

func NewMsgServiceClient(cc *grpc.ClientConn) MsgServiceClient {
	return &msgServiceClient{cc}
}

func (c *msgServiceClient) Send(ctx context.Context, in *MsgRequest, opts ...grpc.CallOption) (*MsgResp, error) {
	out := new(MsgResp)
	err := c.cc.Invoke(ctx, "/msgexample.MsgService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServiceServer is the server API for MsgService service.
type MsgServiceServer interface {
	Send(context.Context, *MsgRequest) (*MsgResp, error)
}

// UnimplementedMsgServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServiceServer struct {
}

func (*UnimplementedMsgServiceServer) Send(ctx context.Context, req *MsgRequest) (*MsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}

func RegisterMsgServiceServer(s *grpc.Server, srv MsgServiceServer) {
	s.RegisterService(&_MsgService_serviceDesc, srv)
}

func _MsgService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msgexample.MsgService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).Send(ctx, req.(*MsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MsgService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "msgexample.MsgService",
	HandlerType: (*MsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _MsgService_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg.proto",
}
